# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from devdraft.models.aggregated_balance_response import AggregatedBalanceResponse
from typing import Optional, Set
from typing_extensions import Self

class AllBalancesResponse(BaseModel):
    """
    AllBalancesResponse
    """ # noqa: E501
    usdc: AggregatedBalanceResponse = Field(description="USDC balance aggregation")
    eurc: AggregatedBalanceResponse = Field(description="EURC balance aggregation")
    total_usd_value: StrictStr = Field(description="Total value in USD equivalent")
    __properties: ClassVar[List[str]] = ["usdc", "eurc", "total_usd_value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AllBalancesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usdc
        if self.usdc:
            _dict['usdc'] = self.usdc.to_dict()
        # override the default output from pydantic by calling `to_dict()` of eurc
        if self.eurc:
            _dict['eurc'] = self.eurc.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AllBalancesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "usdc": AggregatedBalanceResponse.from_dict(obj["usdc"]) if obj.get("usdc") is not None else None,
            "eurc": AggregatedBalanceResponse.from_dict(obj["eurc"]) if obj.get("eurc") is not None else None,
            "total_usd_value": obj.get("total_usd_value")
        })
        return _obj


