# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BridgeFiatPaymentRail(str, Enum):
    """
    The destination payment rail (fiat payment method)
    """

    """
    allowed enum values
    """
    ACH = 'ach'
    ACH_PUSH = 'ach_push'
    ACH_SAME_DAY = 'ach_same_day'
    WIRE = 'wire'
    SEPA = 'sepa'
    SWIFT = 'swift'
    SPEI = 'spei'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BridgeFiatPaymentRail from a JSON string"""
        return cls(json.loads(json_str))


