# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from devdraft.models.bridge_payment_rail import BridgePaymentRail
from devdraft.models.fiat_currency import FiatCurrency
from devdraft.models.stable_coin_currency import StableCoinCurrency
from typing import Optional, Set
from typing_extensions import Self

class CreateBankPaymentIntentDto(BaseModel):
    """
    CreateBankPaymentIntentDto
    """ # noqa: E501
    source_payment_rail: BridgePaymentRail = Field(description="The banking payment method to use for the transfer. Determines processing time and fees.", alias="sourcePaymentRail")
    source_currency: FiatCurrency = Field(description="The fiat currency to convert FROM. Must match the currency of the source payment rail.", alias="sourceCurrency")
    destination_currency: StableCoinCurrency = Field(description="The stablecoin currency to convert TO. The customer will receive this currency.", alias="destinationCurrency")
    destination_network: BridgePaymentRail = Field(description="The blockchain network where the stablecoin will be delivered. Must support the destination currency.", alias="destinationNetwork")
    destination_address: Optional[StrictStr] = Field(default=None, description="Destination wallet address. Supports Ethereum (0x...) and Solana address formats.", alias="destinationAddress")
    amount: Optional[StrictStr] = Field(default=None, description="Payment amount (optional for flexible amount)")
    customer_first_name: Optional[StrictStr] = Field(default=None, description="Customer first name")
    customer_last_name: Optional[StrictStr] = Field(default=None, description="Customer last name")
    customer_email: Optional[StrictStr] = Field(default=None, description="Customer email address")
    customer_address: Optional[StrictStr] = Field(default=None, description="Customer address")
    customer_country: Optional[StrictStr] = Field(default=None, description="Customer country")
    customer_country_iso: Optional[StrictStr] = Field(default=None, description="Customer country ISO code", alias="customer_countryISO")
    customer_province: Optional[StrictStr] = Field(default=None, description="Customer province/state")
    customer_province_iso: Optional[StrictStr] = Field(default=None, description="Customer province/state ISO code", alias="customer_provinceISO")
    phone_number: Optional[StrictStr] = Field(default=None, description="Customer phone number", alias="phoneNumber")
    wire_message: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="Wire transfer message (for WIRE transfers)")
    sepa_reference: Optional[Annotated[str, Field(min_length=6, strict=True, max_length=140)]] = Field(default=None, description="SEPA reference (for SEPA transfers)")
    ach_reference: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="ACH reference (for ACH transfers)")
    __properties: ClassVar[List[str]] = ["sourcePaymentRail", "sourceCurrency", "destinationCurrency", "destinationNetwork", "destinationAddress", "amount", "customer_first_name", "customer_last_name", "customer_email", "customer_address", "customer_country", "customer_countryISO", "customer_province", "customer_provinceISO", "phoneNumber", "wire_message", "sepa_reference", "ach_reference"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateBankPaymentIntentDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateBankPaymentIntentDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourcePaymentRail": obj.get("sourcePaymentRail"),
            "sourceCurrency": obj.get("sourceCurrency"),
            "destinationCurrency": obj.get("destinationCurrency"),
            "destinationNetwork": obj.get("destinationNetwork"),
            "destinationAddress": obj.get("destinationAddress"),
            "amount": obj.get("amount"),
            "customer_first_name": obj.get("customer_first_name"),
            "customer_last_name": obj.get("customer_last_name"),
            "customer_email": obj.get("customer_email"),
            "customer_address": obj.get("customer_address"),
            "customer_country": obj.get("customer_country"),
            "customer_countryISO": obj.get("customer_countryISO"),
            "customer_province": obj.get("customer_province"),
            "customer_provinceISO": obj.get("customer_provinceISO"),
            "phoneNumber": obj.get("phoneNumber"),
            "wire_message": obj.get("wire_message"),
            "sepa_reference": obj.get("sepa_reference"),
            "ach_reference": obj.get("ach_reference")
        })
        return _obj


