/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateInvoiceDto
 */
class CreateInvoiceDtoTest {
    private final CreateInvoiceDto model = new CreateInvoiceDto();

    /**
     * Model tests for CreateInvoiceDto
     */
    @Test
    void testCreateInvoiceDto() {
        // TODO: test CreateInvoiceDto
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'delivery'
     */
    @Test
    void deliveryTest() {
        // TODO: test delivery
    }

    /**
     * Test the property 'paymentLink'
     */
    @Test
    void paymentLinkTest() {
        // TODO: test paymentLink
    }

    /**
     * Test the property 'paymentMethods'
     */
    @Test
    void paymentMethodsTest() {
        // TODO: test paymentMethods
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'sendDate'
     */
    @Test
    void sendDateTest() {
        // TODO: test sendDate
    }

    /**
     * Test the property 'logo'
     */
    @Test
    void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'partialPayment'
     */
    @Test
    void partialPaymentTest() {
        // TODO: test partialPayment
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    void taxIdTest() {
        // TODO: test taxId
    }

}
