/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDirectBankTransferDto
 */
class CreateDirectBankTransferDtoTest {
    private final CreateDirectBankTransferDto model = new CreateDirectBankTransferDto();

    /**
     * Model tests for CreateDirectBankTransferDto
     */
    @Test
    void testCreateDirectBankTransferDto() {
        // TODO: test CreateDirectBankTransferDto
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    void walletIdTest() {
        // TODO: test walletId
    }

    /**
     * Test the property 'paymentRail'
     */
    @Test
    void paymentRailTest() {
        // TODO: test paymentRail
    }

    /**
     * Test the property 'destinationCurrency'
     */
    @Test
    void destinationCurrencyTest() {
        // TODO: test destinationCurrency
    }

    /**
     * Test the property 'sourceCurrency'
     */
    @Test
    void sourceCurrencyTest() {
        // TODO: test sourceCurrency
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'wireMessage'
     */
    @Test
    void wireMessageTest() {
        // TODO: test wireMessage
    }

    /**
     * Test the property 'sepaReference'
     */
    @Test
    void sepaReferenceTest() {
        // TODO: test sepaReference
    }

    /**
     * Test the property 'achReference'
     */
    @Test
    void achReferenceTest() {
        // TODO: test achReference
    }

}
