/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceProductDto
 */
class InvoiceProductDtoTest {
    private final InvoiceProductDto model = new InvoiceProductDto();

    /**
     * Model tests for InvoiceProductDto
     */
    @Test
    void testInvoiceProductDto() {
        // TODO: test InvoiceProductDto
    }

    /**
     * Test the property 'productId'
     */
    @Test
    void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

}
