# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.create_direct_bank_transfer_dto import CreateDirectBankTransferDto

class TestCreateDirectBankTransferDto(unittest.TestCase):
    """CreateDirectBankTransferDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDirectBankTransferDto:
        """Test CreateDirectBankTransferDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDirectBankTransferDto`
        """
        model = CreateDirectBankTransferDto()
        if include_optional:
            return CreateDirectBankTransferDto(
                wallet_id = '',
                payment_rail = '',
                destination_currency = '',
                source_currency = '',
                amount = 1.337,
                wire_message = '',
                sepa_reference = '',
                ach_reference = ''
            )
        else:
            return CreateDirectBankTransferDto(
                wallet_id = '',
                payment_rail = '',
                destination_currency = '',
                source_currency = '',
                amount = 1.337,
        )
        """

    def testCreateDirectBankTransferDto(self):
        """Test CreateDirectBankTransferDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
