# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.tax_controller_create201_response import TaxControllerCreate201Response

class TestTaxControllerCreate201Response(unittest.TestCase):
    """TaxControllerCreate201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxControllerCreate201Response:
        """Test TaxControllerCreate201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxControllerCreate201Response`
        """
        model = TaxControllerCreate201Response()
        if include_optional:
            return TaxControllerCreate201Response(
                id = 'tax_123e4567-e89b-12d3-a456-426614174000',
                name = 'Sales Tax',
                description = 'Standard sales tax for retail transactions',
                percentage = 8.5,
                active = True,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TaxControllerCreate201Response(
        )
        """

    def testTaxControllerCreate201Response(self):
        """Test TaxControllerCreate201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
