# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.create_stablecoin_conversion_dto import CreateStablecoinConversionDto

class TestCreateStablecoinConversionDto(unittest.TestCase):
    """CreateStablecoinConversionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateStablecoinConversionDto:
        """Test CreateStablecoinConversionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateStablecoinConversionDto`
        """
        model = CreateStablecoinConversionDto()
        if include_optional:
            return CreateStablecoinConversionDto(
                wallet_id = '',
                source_network = '',
                source_currency = '',
                destination_currency = '',
                amount = 1.337
            )
        else:
            return CreateStablecoinConversionDto(
                wallet_id = '',
                source_network = '',
                source_currency = '',
                destination_currency = '',
                amount = 1.337,
        )
        """

    def testCreateStablecoinConversionDto(self):
        """Test CreateStablecoinConversionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
