# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.payment_response_dto import PaymentResponseDto

class TestPaymentResponseDto(unittest.TestCase):
    """PaymentResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentResponseDto:
        """Test PaymentResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentResponseDto`
        """
        model = PaymentResponseDto()
        if include_optional:
            return PaymentResponseDto(
                id = 'pay_12345abcdef',
                amount = 100.5,
                currency = 'USD',
                status = 'succeeded',
                timestamp = '2023-07-01T12:00:00.000Z'
            )
        else:
            return PaymentResponseDto(
                id = 'pay_12345abcdef',
                amount = 100.5,
                currency = 'USD',
                status = 'succeeded',
                timestamp = '2023-07-01T12:00:00.000Z',
        )
        """

    def testPaymentResponseDto(self):
        """Test PaymentResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
