# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.bridge_payment_rail import BridgePaymentRail

class TestBridgePaymentRail(unittest.TestCase):
    """BridgePaymentRail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBridgePaymentRail(self):
        """Test BridgePaymentRail"""
        # inst = BridgePaymentRail()

if __name__ == '__main__':
    unittest.main()
