# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.models.create_liquidation_address_dto import CreateLiquidationAddressDto

class TestCreateLiquidationAddressDto(unittest.TestCase):
    """CreateLiquidationAddressDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLiquidationAddressDto:
        """Test CreateLiquidationAddressDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLiquidationAddressDto`
        """
        model = CreateLiquidationAddressDto()
        if include_optional:
            return CreateLiquidationAddressDto(
                chain = 'ethereum',
                currency = 'usdc',
                address = '0x4d0280da2f2fDA5103914bCc5aad114743152A9c',
                external_account_id = 'ext_123',
                prefunded_account_id = 'pf_acc_123',
                bridge_wallet_id = 'bw_123',
                destination_payment_rail = 'ethereum',
                destination_currency = 'usd',
                destination_wire_message = 'Liquidation payment for customer',
                destination_sepa_reference = 'SEPA-REF-123456',
                destination_ach_reference = 'ACH123',
                destination_address = '0x1234567890abcdef1234567890abcdef12345678',
                destination_blockchain_memo = 'liquidation-memo-123',
                return_address = '0xabcdefabcdefabcdefabcdefabcdefabcdef',
                custom_developer_fee_percent = '2.5'
            )
        else:
            return CreateLiquidationAddressDto(
                chain = 'ethereum',
                currency = 'usdc',
                address = '0x4d0280da2f2fDA5103914bCc5aad114743152A9c',
        )
        """

    def testCreateLiquidationAddressDto(self):
        """Test CreateLiquidationAddressDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
