# coding: utf-8

"""
    Devdraft AI Payment & Business Management API

     A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from devdraft.api.wallets_api import WalletsApi


class TestWalletsApi(unittest.TestCase):
    """WalletsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WalletsApi()

    def tearDown(self) -> None:
        pass

    def test_wallet_controller_get_wallets(self) -> None:
        """Test case for wallet_controller_get_wallets

        Get wallets for an app
        """
        pass


if __name__ == '__main__':
    unittest.main()
