/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// TransfersAPIService TransfersAPI service
type TransfersAPIService service

type ApiTransferControllerCreateDirectBankTransferRequest struct {
	ctx context.Context
	ApiService *TransfersAPIService
	createDirectBankTransferDto *CreateDirectBankTransferDto
}

func (r ApiTransferControllerCreateDirectBankTransferRequest) CreateDirectBankTransferDto(createDirectBankTransferDto CreateDirectBankTransferDto) ApiTransferControllerCreateDirectBankTransferRequest {
	r.createDirectBankTransferDto = &createDirectBankTransferDto
	return r
}

func (r ApiTransferControllerCreateDirectBankTransferRequest) Execute() (*http.Response, error) {
	return r.ApiService.TransferControllerCreateDirectBankTransferExecute(r)
}

/*
TransferControllerCreateDirectBankTransfer Create a direct bank transfer

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTransferControllerCreateDirectBankTransferRequest
*/
func (a *TransfersAPIService) TransferControllerCreateDirectBankTransfer(ctx context.Context) ApiTransferControllerCreateDirectBankTransferRequest {
	return ApiTransferControllerCreateDirectBankTransferRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *TransfersAPIService) TransferControllerCreateDirectBankTransferExecute(r ApiTransferControllerCreateDirectBankTransferRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransfersAPIService.TransferControllerCreateDirectBankTransfer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v0/transfers/direct-bank"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createDirectBankTransferDto == nil {
		return nil, reportError("createDirectBankTransferDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createDirectBankTransferDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-secret"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-secret"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiTransferControllerCreateDirectWalletTransferRequest struct {
	ctx context.Context
	ApiService *TransfersAPIService
	createDirectWalletTransferDto *CreateDirectWalletTransferDto
}

func (r ApiTransferControllerCreateDirectWalletTransferRequest) CreateDirectWalletTransferDto(createDirectWalletTransferDto CreateDirectWalletTransferDto) ApiTransferControllerCreateDirectWalletTransferRequest {
	r.createDirectWalletTransferDto = &createDirectWalletTransferDto
	return r
}

func (r ApiTransferControllerCreateDirectWalletTransferRequest) Execute() (*http.Response, error) {
	return r.ApiService.TransferControllerCreateDirectWalletTransferExecute(r)
}

/*
TransferControllerCreateDirectWalletTransfer Create a direct wallet transfer

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTransferControllerCreateDirectWalletTransferRequest
*/
func (a *TransfersAPIService) TransferControllerCreateDirectWalletTransfer(ctx context.Context) ApiTransferControllerCreateDirectWalletTransferRequest {
	return ApiTransferControllerCreateDirectWalletTransferRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *TransfersAPIService) TransferControllerCreateDirectWalletTransferExecute(r ApiTransferControllerCreateDirectWalletTransferRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransfersAPIService.TransferControllerCreateDirectWalletTransfer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v0/transfers/direct-wallet"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createDirectWalletTransferDto == nil {
		return nil, reportError("createDirectWalletTransferDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createDirectWalletTransferDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-secret"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-secret"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiTransferControllerCreateExternalBankTransferRequest struct {
	ctx context.Context
	ApiService *TransfersAPIService
	createExternalBankTransferDto *CreateExternalBankTransferDto
}

func (r ApiTransferControllerCreateExternalBankTransferRequest) CreateExternalBankTransferDto(createExternalBankTransferDto CreateExternalBankTransferDto) ApiTransferControllerCreateExternalBankTransferRequest {
	r.createExternalBankTransferDto = &createExternalBankTransferDto
	return r
}

func (r ApiTransferControllerCreateExternalBankTransferRequest) Execute() (*http.Response, error) {
	return r.ApiService.TransferControllerCreateExternalBankTransferExecute(r)
}

/*
TransferControllerCreateExternalBankTransfer Create an external bank transfer

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTransferControllerCreateExternalBankTransferRequest
*/
func (a *TransfersAPIService) TransferControllerCreateExternalBankTransfer(ctx context.Context) ApiTransferControllerCreateExternalBankTransferRequest {
	return ApiTransferControllerCreateExternalBankTransferRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *TransfersAPIService) TransferControllerCreateExternalBankTransferExecute(r ApiTransferControllerCreateExternalBankTransferRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransfersAPIService.TransferControllerCreateExternalBankTransfer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v0/transfers/external-bank-transfer"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createExternalBankTransferDto == nil {
		return nil, reportError("createExternalBankTransferDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createExternalBankTransferDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-secret"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-secret"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiTransferControllerCreateExternalStablecoinTransferRequest struct {
	ctx context.Context
	ApiService *TransfersAPIService
	createExternalStablecoinTransferDto *CreateExternalStablecoinTransferDto
}

func (r ApiTransferControllerCreateExternalStablecoinTransferRequest) CreateExternalStablecoinTransferDto(createExternalStablecoinTransferDto CreateExternalStablecoinTransferDto) ApiTransferControllerCreateExternalStablecoinTransferRequest {
	r.createExternalStablecoinTransferDto = &createExternalStablecoinTransferDto
	return r
}

func (r ApiTransferControllerCreateExternalStablecoinTransferRequest) Execute() (*http.Response, error) {
	return r.ApiService.TransferControllerCreateExternalStablecoinTransferExecute(r)
}

/*
TransferControllerCreateExternalStablecoinTransfer Create an external stablecoin transfer

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTransferControllerCreateExternalStablecoinTransferRequest
*/
func (a *TransfersAPIService) TransferControllerCreateExternalStablecoinTransfer(ctx context.Context) ApiTransferControllerCreateExternalStablecoinTransferRequest {
	return ApiTransferControllerCreateExternalStablecoinTransferRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *TransfersAPIService) TransferControllerCreateExternalStablecoinTransferExecute(r ApiTransferControllerCreateExternalStablecoinTransferRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransfersAPIService.TransferControllerCreateExternalStablecoinTransfer")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v0/transfers/external-stablecoin-transfer"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createExternalStablecoinTransferDto == nil {
		return nil, reportError("createExternalStablecoinTransferDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createExternalStablecoinTransferDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-secret"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-secret"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiTransferControllerCreateStablecoinConversionRequest struct {
	ctx context.Context
	ApiService *TransfersAPIService
	createStablecoinConversionDto *CreateStablecoinConversionDto
}

func (r ApiTransferControllerCreateStablecoinConversionRequest) CreateStablecoinConversionDto(createStablecoinConversionDto CreateStablecoinConversionDto) ApiTransferControllerCreateStablecoinConversionRequest {
	r.createStablecoinConversionDto = &createStablecoinConversionDto
	return r
}

func (r ApiTransferControllerCreateStablecoinConversionRequest) Execute() (*http.Response, error) {
	return r.ApiService.TransferControllerCreateStablecoinConversionExecute(r)
}

/*
TransferControllerCreateStablecoinConversion Create a stablecoin conversion

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTransferControllerCreateStablecoinConversionRequest
*/
func (a *TransfersAPIService) TransferControllerCreateStablecoinConversion(ctx context.Context) ApiTransferControllerCreateStablecoinConversionRequest {
	return ApiTransferControllerCreateStablecoinConversionRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *TransfersAPIService) TransferControllerCreateStablecoinConversionExecute(r ApiTransferControllerCreateStablecoinConversionRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TransfersAPIService.TransferControllerCreateStablecoinConversion")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v0/transfers/stablecoin-conversion"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createStablecoinConversionDto == nil {
		return nil, reportError("createStablecoinConversionDto is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createStablecoinConversionDto
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-secret"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-secret"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["x-client-key"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["x-client-key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
