/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"encoding/json"
	"fmt"
)

// DestinationCurrency Currency for sending funds
type DestinationCurrency string

// List of DestinationCurrency
const (
	USD DestinationCurrency = "usd"
	EUR DestinationCurrency = "eur"
	MXN DestinationCurrency = "mxn"
	USDC DestinationCurrency = "usdc"
	EURC DestinationCurrency = "eurc"
	DAI DestinationCurrency = "dai"
	PYUSD DestinationCurrency = "pyusd"
	USDT DestinationCurrency = "usdt"
)

// All allowed values of DestinationCurrency enum
var AllowedDestinationCurrencyEnumValues = []DestinationCurrency{
	"usd",
	"eur",
	"mxn",
	"usdc",
	"eurc",
	"dai",
	"pyusd",
	"usdt",
}

func (v *DestinationCurrency) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DestinationCurrency(value)
	for _, existing := range AllowedDestinationCurrencyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DestinationCurrency", value)
}

// NewDestinationCurrencyFromValue returns a pointer to a valid DestinationCurrency
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDestinationCurrencyFromValue(v string) (*DestinationCurrency, error) {
	ev := DestinationCurrency(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DestinationCurrency: valid values are %v", v, AllowedDestinationCurrencyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DestinationCurrency) IsValid() bool {
	for _, existing := range AllowedDestinationCurrencyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DestinationCurrency value
func (v DestinationCurrency) Ptr() *DestinationCurrency {
	return &v
}

type NullableDestinationCurrency struct {
	value *DestinationCurrency
	isSet bool
}

func (v NullableDestinationCurrency) Get() *DestinationCurrency {
	return v.value
}

func (v *NullableDestinationCurrency) Set(val *DestinationCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationCurrency(val *DestinationCurrency) *NullableDestinationCurrency {
	return &NullableDestinationCurrency{value: val, isSet: true}
}

func (v NullableDestinationCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

