/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HealthResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthResponseDto{}

// HealthResponseDto struct for HealthResponseDto
type HealthResponseDto struct {
	// Overall health status of the service. Returns \"ok\" when healthy, \"error\" when issues detected.
	Status string `json:"status"`
	// ISO 8601 timestamp when the health check was performed.
	Timestamp time.Time `json:"timestamp"`
	// Current version of the API service. Useful for debugging and compatibility checks.
	Version string `json:"version"`
	// Database connectivity status. Shows \"connected\" when database is accessible, \"error\" when connection fails.
	Database string `json:"database"`
	// Human-readable message describing the current health status and any issues.
	Message string `json:"message"`
	// Indicates whether the request was properly authenticated. Always true for this endpoint since authentication is required.
	Authenticated bool `json:"authenticated"`
}

type _HealthResponseDto HealthResponseDto

// NewHealthResponseDto instantiates a new HealthResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthResponseDto(status string, timestamp time.Time, version string, database string, message string, authenticated bool) *HealthResponseDto {
	this := HealthResponseDto{}
	this.Status = status
	this.Timestamp = timestamp
	this.Version = version
	this.Database = database
	this.Message = message
	this.Authenticated = authenticated
	return &this
}

// NewHealthResponseDtoWithDefaults instantiates a new HealthResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthResponseDtoWithDefaults() *HealthResponseDto {
	this := HealthResponseDto{}
	return &this
}

// GetStatus returns the Status field value
func (o *HealthResponseDto) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthResponseDto) SetStatus(v string) {
	o.Status = v
}

// GetTimestamp returns the Timestamp field value
func (o *HealthResponseDto) GetTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *HealthResponseDto) SetTimestamp(v time.Time) {
	o.Timestamp = v
}

// GetVersion returns the Version field value
func (o *HealthResponseDto) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HealthResponseDto) SetVersion(v string) {
	o.Version = v
}

// GetDatabase returns the Database field value
func (o *HealthResponseDto) GetDatabase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Database
}

// GetDatabaseOk returns a tuple with the Database field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetDatabaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Database, true
}

// SetDatabase sets field value
func (o *HealthResponseDto) SetDatabase(v string) {
	o.Database = v
}

// GetMessage returns the Message field value
func (o *HealthResponseDto) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *HealthResponseDto) SetMessage(v string) {
	o.Message = v
}

// GetAuthenticated returns the Authenticated field value
func (o *HealthResponseDto) GetAuthenticated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Authenticated
}

// GetAuthenticatedOk returns a tuple with the Authenticated field value
// and a boolean to check if the value has been set.
func (o *HealthResponseDto) GetAuthenticatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authenticated, true
}

// SetAuthenticated sets field value
func (o *HealthResponseDto) SetAuthenticated(v bool) {
	o.Authenticated = v
}

func (o HealthResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["version"] = o.Version
	toSerialize["database"] = o.Database
	toSerialize["message"] = o.Message
	toSerialize["authenticated"] = o.Authenticated
	return toSerialize, nil
}

func (o *HealthResponseDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"timestamp",
		"version",
		"database",
		"message",
		"authenticated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthResponseDto := _HealthResponseDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthResponseDto)

	if err != nil {
		return err
	}

	*o = HealthResponseDto(varHealthResponseDto)

	return err
}

type NullableHealthResponseDto struct {
	value *HealthResponseDto
	isSet bool
}

func (v NullableHealthResponseDto) Get() *HealthResponseDto {
	return v.value
}

func (v *NullableHealthResponseDto) Set(val *HealthResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthResponseDto(val *HealthResponseDto) *NullableHealthResponseDto {
	return &NullableHealthResponseDto{value: val, isSet: true}
}

func (v NullableHealthResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


