/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateExternalStablecoinTransferDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateExternalStablecoinTransferDto{}

// CreateExternalStablecoinTransferDto struct for CreateExternalStablecoinTransferDto
type CreateExternalStablecoinTransferDto struct {
	// The ID of the source bridge wallet
	SourceWalletId string `json:"sourceWalletId"`
	// The source currency
	SourceCurrency string `json:"sourceCurrency"`
	// The destination currency
	DestinationCurrency string `json:"destinationCurrency"`
	// Blockchain memo for the transfer
	BlockchainMemo *string `json:"blockchain_memo,omitempty"`
	// Beneficiary ID for the stablecoin transfer
	BeneficiaryId string `json:"beneficiaryId"`
	// The amount to transfer
	Amount *float32 `json:"amount,omitempty"`
}

type _CreateExternalStablecoinTransferDto CreateExternalStablecoinTransferDto

// NewCreateExternalStablecoinTransferDto instantiates a new CreateExternalStablecoinTransferDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateExternalStablecoinTransferDto(sourceWalletId string, sourceCurrency string, destinationCurrency string, beneficiaryId string) *CreateExternalStablecoinTransferDto {
	this := CreateExternalStablecoinTransferDto{}
	this.SourceWalletId = sourceWalletId
	this.SourceCurrency = sourceCurrency
	this.DestinationCurrency = destinationCurrency
	this.BeneficiaryId = beneficiaryId
	return &this
}

// NewCreateExternalStablecoinTransferDtoWithDefaults instantiates a new CreateExternalStablecoinTransferDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateExternalStablecoinTransferDtoWithDefaults() *CreateExternalStablecoinTransferDto {
	this := CreateExternalStablecoinTransferDto{}
	return &this
}

// GetSourceWalletId returns the SourceWalletId field value
func (o *CreateExternalStablecoinTransferDto) GetSourceWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceWalletId
}

// GetSourceWalletIdOk returns a tuple with the SourceWalletId field value
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetSourceWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceWalletId, true
}

// SetSourceWalletId sets field value
func (o *CreateExternalStablecoinTransferDto) SetSourceWalletId(v string) {
	o.SourceWalletId = v
}

// GetSourceCurrency returns the SourceCurrency field value
func (o *CreateExternalStablecoinTransferDto) GetSourceCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceCurrency
}

// GetSourceCurrencyOk returns a tuple with the SourceCurrency field value
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetSourceCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceCurrency, true
}

// SetSourceCurrency sets field value
func (o *CreateExternalStablecoinTransferDto) SetSourceCurrency(v string) {
	o.SourceCurrency = v
}

// GetDestinationCurrency returns the DestinationCurrency field value
func (o *CreateExternalStablecoinTransferDto) GetDestinationCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationCurrency
}

// GetDestinationCurrencyOk returns a tuple with the DestinationCurrency field value
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetDestinationCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationCurrency, true
}

// SetDestinationCurrency sets field value
func (o *CreateExternalStablecoinTransferDto) SetDestinationCurrency(v string) {
	o.DestinationCurrency = v
}

// GetBlockchainMemo returns the BlockchainMemo field value if set, zero value otherwise.
func (o *CreateExternalStablecoinTransferDto) GetBlockchainMemo() string {
	if o == nil || IsNil(o.BlockchainMemo) {
		var ret string
		return ret
	}
	return *o.BlockchainMemo
}

// GetBlockchainMemoOk returns a tuple with the BlockchainMemo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetBlockchainMemoOk() (*string, bool) {
	if o == nil || IsNil(o.BlockchainMemo) {
		return nil, false
	}
	return o.BlockchainMemo, true
}

// HasBlockchainMemo returns a boolean if a field has been set.
func (o *CreateExternalStablecoinTransferDto) HasBlockchainMemo() bool {
	if o != nil && !IsNil(o.BlockchainMemo) {
		return true
	}

	return false
}

// SetBlockchainMemo gets a reference to the given string and assigns it to the BlockchainMemo field.
func (o *CreateExternalStablecoinTransferDto) SetBlockchainMemo(v string) {
	o.BlockchainMemo = &v
}

// GetBeneficiaryId returns the BeneficiaryId field value
func (o *CreateExternalStablecoinTransferDto) GetBeneficiaryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BeneficiaryId
}

// GetBeneficiaryIdOk returns a tuple with the BeneficiaryId field value
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetBeneficiaryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BeneficiaryId, true
}

// SetBeneficiaryId sets field value
func (o *CreateExternalStablecoinTransferDto) SetBeneficiaryId(v string) {
	o.BeneficiaryId = v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *CreateExternalStablecoinTransferDto) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateExternalStablecoinTransferDto) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *CreateExternalStablecoinTransferDto) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *CreateExternalStablecoinTransferDto) SetAmount(v float32) {
	o.Amount = &v
}

func (o CreateExternalStablecoinTransferDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateExternalStablecoinTransferDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sourceWalletId"] = o.SourceWalletId
	toSerialize["sourceCurrency"] = o.SourceCurrency
	toSerialize["destinationCurrency"] = o.DestinationCurrency
	if !IsNil(o.BlockchainMemo) {
		toSerialize["blockchain_memo"] = o.BlockchainMemo
	}
	toSerialize["beneficiaryId"] = o.BeneficiaryId
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	return toSerialize, nil
}

func (o *CreateExternalStablecoinTransferDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sourceWalletId",
		"sourceCurrency",
		"destinationCurrency",
		"beneficiaryId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateExternalStablecoinTransferDto := _CreateExternalStablecoinTransferDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateExternalStablecoinTransferDto)

	if err != nil {
		return err
	}

	*o = CreateExternalStablecoinTransferDto(varCreateExternalStablecoinTransferDto)

	return err
}

type NullableCreateExternalStablecoinTransferDto struct {
	value *CreateExternalStablecoinTransferDto
	isSet bool
}

func (v NullableCreateExternalStablecoinTransferDto) Get() *CreateExternalStablecoinTransferDto {
	return v.value
}

func (v *NullableCreateExternalStablecoinTransferDto) Set(val *CreateExternalStablecoinTransferDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateExternalStablecoinTransferDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateExternalStablecoinTransferDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateExternalStablecoinTransferDto(val *CreateExternalStablecoinTransferDto) *NullableCreateExternalStablecoinTransferDto {
	return &NullableCreateExternalStablecoinTransferDto{value: val, isSet: true}
}

func (v NullableCreateExternalStablecoinTransferDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateExternalStablecoinTransferDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


