/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"encoding/json"
	"fmt"
)

// BridgePaymentRail The blockchain network where the source currency resides. Determines gas fees and transaction speed.
type BridgePaymentRail string

// List of BridgePaymentRail
const (
	ETHEREUM BridgePaymentRail = "ethereum"
	SOLANA BridgePaymentRail = "solana"
	POLYGON BridgePaymentRail = "polygon"
	AVALANCHE_C_CHAIN BridgePaymentRail = "avalanche_c_chain"
	BASE BridgePaymentRail = "base"
	ARBITRUM BridgePaymentRail = "arbitrum"
	OPTIMISM BridgePaymentRail = "optimism"
	STELLAR BridgePaymentRail = "stellar"
	TRON BridgePaymentRail = "tron"
	BRIDGE_WALLET BridgePaymentRail = "bridge_wallet"
	WIRE BridgePaymentRail = "wire"
	ACH BridgePaymentRail = "ach"
	ACH_PUSH BridgePaymentRail = "ach_push"
	ACH_SAME_DAY BridgePaymentRail = "ach_same_day"
	SEPA BridgePaymentRail = "sepa"
	SWIFT BridgePaymentRail = "swift"
	SPEI BridgePaymentRail = "spei"
)

// All allowed values of BridgePaymentRail enum
var AllowedBridgePaymentRailEnumValues = []BridgePaymentRail{
	"ethereum",
	"solana",
	"polygon",
	"avalanche_c_chain",
	"base",
	"arbitrum",
	"optimism",
	"stellar",
	"tron",
	"bridge_wallet",
	"wire",
	"ach",
	"ach_push",
	"ach_same_day",
	"sepa",
	"swift",
	"spei",
}

func (v *BridgePaymentRail) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BridgePaymentRail(value)
	for _, existing := range AllowedBridgePaymentRailEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BridgePaymentRail", value)
}

// NewBridgePaymentRailFromValue returns a pointer to a valid BridgePaymentRail
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBridgePaymentRailFromValue(v string) (*BridgePaymentRail, error) {
	ev := BridgePaymentRail(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BridgePaymentRail: valid values are %v", v, AllowedBridgePaymentRailEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BridgePaymentRail) IsValid() bool {
	for _, existing := range AllowedBridgePaymentRailEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BridgePaymentRail value
func (v BridgePaymentRail) Ptr() *BridgePaymentRail {
	return &v
}

type NullableBridgePaymentRail struct {
	value *BridgePaymentRail
	isSet bool
}

func (v NullableBridgePaymentRail) Get() *BridgePaymentRail {
	return v.value
}

func (v *NullableBridgePaymentRail) Set(val *BridgePaymentRail) {
	v.value = val
	v.isSet = true
}

func (v NullableBridgePaymentRail) IsSet() bool {
	return v.isSet
}

func (v *NullableBridgePaymentRail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBridgePaymentRail(val *BridgePaymentRail) *NullableBridgePaymentRail {
	return &NullableBridgePaymentRail{value: val, isSet: true}
}

func (v NullableBridgePaymentRail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBridgePaymentRail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

