/*
Devdraft AI Payment & Business Management API

 A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package devdraft

import (
	"encoding/json"
	"fmt"
)

// CustomerType Type of customer account. Determines available features and compliance requirements.
type CustomerType string

// List of CustomerType
const (
	INDIVIDUAL CustomerType = "Individual"
	STARTUP CustomerType = "Startup"
	SMALL_BUSINESS CustomerType = "Small Business"
	MEDIUM_BUSINESS CustomerType = "Medium Business"
	ENTERPRISE CustomerType = "Enterprise"
	NON_PROFIT CustomerType = "Non-Profit"
	GOVERNMENT CustomerType = "Government"
)

// All allowed values of CustomerType enum
var AllowedCustomerTypeEnumValues = []CustomerType{
	"Individual",
	"Startup",
	"Small Business",
	"Medium Business",
	"Enterprise",
	"Non-Profit",
	"Government",
}

func (v *CustomerType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustomerType(value)
	for _, existing := range AllowedCustomerTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustomerType", value)
}

// NewCustomerTypeFromValue returns a pointer to a valid CustomerType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustomerTypeFromValue(v string) (*CustomerType, error) {
	ev := CustomerType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustomerType: valid values are %v", v, AllowedCustomerTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustomerType) IsValid() bool {
	for _, existing := range AllowedCustomerTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustomerType value
func (v CustomerType) Ptr() *CustomerType {
	return &v
}

type NullableCustomerType struct {
	value *CustomerType
	isSet bool
}

func (v NullableCustomerType) Get() *CustomerType {
	return v.value
}

func (v *NullableCustomerType) Set(val *CustomerType) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerType) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerType(val *CustomerType) *NullableCustomerType {
	return &NullableCustomerType{value: val, isSet: true}
}

func (v NullableCustomerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

