/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import org.openapitools.client.model.CreateLiquidationAddressDto;
import org.openapitools.client.model.LiquidationAddressResponseDto;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-19T14:30:15.336690+02:00[Africa/Lusaka]", comments = "Generator version: 7.17.0")
public class LiquidationAddressesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public LiquidationAddressesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public LiquidationAddressesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a new liquidation address for a customer
   *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer&#39;s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
   * @param customerId Unique identifier for the customer (required)
   * @param createLiquidationAddressDto  (required)
   * @return LiquidationAddressResponseDto
   * @throws ApiException if fails to make API call
   */
  public LiquidationAddressResponseDto liquidationAddressControllerCreateLiquidationAddress(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull CreateLiquidationAddressDto createLiquidationAddressDto) throws ApiException {
    return liquidationAddressControllerCreateLiquidationAddress(customerId, createLiquidationAddressDto, null);
  }

  /**
   * Create a new liquidation address for a customer
   *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer&#39;s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
   * @param customerId Unique identifier for the customer (required)
   * @param createLiquidationAddressDto  (required)
   * @param headers Optional headers to include in the request
   * @return LiquidationAddressResponseDto
   * @throws ApiException if fails to make API call
   */
  public LiquidationAddressResponseDto liquidationAddressControllerCreateLiquidationAddress(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull CreateLiquidationAddressDto createLiquidationAddressDto, Map<String, String> headers) throws ApiException {
    ApiResponse<LiquidationAddressResponseDto> localVarResponse = liquidationAddressControllerCreateLiquidationAddressWithHttpInfo(customerId, createLiquidationAddressDto, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a new liquidation address for a customer
   *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer&#39;s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
   * @param customerId Unique identifier for the customer (required)
   * @param createLiquidationAddressDto  (required)
   * @return ApiResponse&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LiquidationAddressResponseDto> liquidationAddressControllerCreateLiquidationAddressWithHttpInfo(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull CreateLiquidationAddressDto createLiquidationAddressDto) throws ApiException {
    return liquidationAddressControllerCreateLiquidationAddressWithHttpInfo(customerId, createLiquidationAddressDto, null);
  }

  /**
   * Create a new liquidation address for a customer
   *        Create a new liquidation address for a customer. Liquidation addresses allow        customers to automatically liquidate cryptocurrency holdings to fiat or other        stablecoins based on configured parameters.        **Required fields:**       - chain: Blockchain network (ethereum, polygon, arbitrum, base)       - currency: Stablecoin currency (usdc, eurc, dai, pyusd, usdt)       - address: Valid blockchain address        **At least one destination must be specified:**       - external_account_id: External bank account       - prefunded_account_id: Developer&#39;s prefunded account       - bridge_wallet_id: Bridge wallet       - destination_address: Crypto wallet address        **Payment Rails:**       Different payment rails have different requirements:       - ACH: Requires external_account_id, supports destination_ach_reference       - SEPA: Requires external_account_id, supports destination_sepa_reference       - Wire: Requires external_account_id, supports destination_wire_message       - Crypto: Requires destination_address, supports destination_blockchain_memo     
   * @param customerId Unique identifier for the customer (required)
   * @param createLiquidationAddressDto  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LiquidationAddressResponseDto> liquidationAddressControllerCreateLiquidationAddressWithHttpInfo(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull CreateLiquidationAddressDto createLiquidationAddressDto, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = liquidationAddressControllerCreateLiquidationAddressRequestBuilder(customerId, createLiquidationAddressDto, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("liquidationAddressControllerCreateLiquidationAddress", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<LiquidationAddressResponseDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        LiquidationAddressResponseDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<LiquidationAddressResponseDto>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<LiquidationAddressResponseDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder liquidationAddressControllerCreateLiquidationAddressRequestBuilder(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull CreateLiquidationAddressDto createLiquidationAddressDto, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'customerId' is set
    if (customerId == null) {
      throw new ApiException(400, "Missing the required parameter 'customerId' when calling liquidationAddressControllerCreateLiquidationAddress");
    }
    // verify the required parameter 'createLiquidationAddressDto' is set
    if (createLiquidationAddressDto == null) {
      throw new ApiException(400, "Missing the required parameter 'createLiquidationAddressDto' when calling liquidationAddressControllerCreateLiquidationAddress");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/customers/{customerId}/liquidation_addresses"
        .replace("{customerId}", ApiClient.urlEncode(customerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createLiquidationAddressDto);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a specific liquidation address
   * Retrieve a specific liquidation address by its ID for a given customer.
   * @param customerId Unique identifier for the customer (required)
   * @param liquidationAddressId Unique identifier for the liquidation address (required)
   * @return LiquidationAddressResponseDto
   * @throws ApiException if fails to make API call
   */
  public LiquidationAddressResponseDto liquidationAddressControllerGetLiquidationAddress(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull String liquidationAddressId) throws ApiException {
    return liquidationAddressControllerGetLiquidationAddress(customerId, liquidationAddressId, null);
  }

  /**
   * Get a specific liquidation address
   * Retrieve a specific liquidation address by its ID for a given customer.
   * @param customerId Unique identifier for the customer (required)
   * @param liquidationAddressId Unique identifier for the liquidation address (required)
   * @param headers Optional headers to include in the request
   * @return LiquidationAddressResponseDto
   * @throws ApiException if fails to make API call
   */
  public LiquidationAddressResponseDto liquidationAddressControllerGetLiquidationAddress(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull String liquidationAddressId, Map<String, String> headers) throws ApiException {
    ApiResponse<LiquidationAddressResponseDto> localVarResponse = liquidationAddressControllerGetLiquidationAddressWithHttpInfo(customerId, liquidationAddressId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a specific liquidation address
   * Retrieve a specific liquidation address by its ID for a given customer.
   * @param customerId Unique identifier for the customer (required)
   * @param liquidationAddressId Unique identifier for the liquidation address (required)
   * @return ApiResponse&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LiquidationAddressResponseDto> liquidationAddressControllerGetLiquidationAddressWithHttpInfo(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull String liquidationAddressId) throws ApiException {
    return liquidationAddressControllerGetLiquidationAddressWithHttpInfo(customerId, liquidationAddressId, null);
  }

  /**
   * Get a specific liquidation address
   * Retrieve a specific liquidation address by its ID for a given customer.
   * @param customerId Unique identifier for the customer (required)
   * @param liquidationAddressId Unique identifier for the liquidation address (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LiquidationAddressResponseDto> liquidationAddressControllerGetLiquidationAddressWithHttpInfo(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull String liquidationAddressId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = liquidationAddressControllerGetLiquidationAddressRequestBuilder(customerId, liquidationAddressId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("liquidationAddressControllerGetLiquidationAddress", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<LiquidationAddressResponseDto>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        LiquidationAddressResponseDto responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<LiquidationAddressResponseDto>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<LiquidationAddressResponseDto>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder liquidationAddressControllerGetLiquidationAddressRequestBuilder(@javax.annotation.Nonnull String customerId, @javax.annotation.Nonnull String liquidationAddressId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'customerId' is set
    if (customerId == null) {
      throw new ApiException(400, "Missing the required parameter 'customerId' when calling liquidationAddressControllerGetLiquidationAddress");
    }
    // verify the required parameter 'liquidationAddressId' is set
    if (liquidationAddressId == null) {
      throw new ApiException(400, "Missing the required parameter 'liquidationAddressId' when calling liquidationAddressControllerGetLiquidationAddress");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/customers/{customerId}/liquidation_addresses/{liquidationAddressId}"
        .replace("{customerId}", ApiClient.urlEncode(customerId.toString()))
        .replace("{liquidationAddressId}", ApiClient.urlEncode(liquidationAddressId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all liquidation addresses for a customer
   * Retrieve all liquidation addresses associated with a specific customer.
   * @param customerId Unique identifier for the customer (required)
   * @return List&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<LiquidationAddressResponseDto> liquidationAddressControllerGetLiquidationAddresses(@javax.annotation.Nonnull String customerId) throws ApiException {
    return liquidationAddressControllerGetLiquidationAddresses(customerId, null);
  }

  /**
   * Get all liquidation addresses for a customer
   * Retrieve all liquidation addresses associated with a specific customer.
   * @param customerId Unique identifier for the customer (required)
   * @param headers Optional headers to include in the request
   * @return List&lt;LiquidationAddressResponseDto&gt;
   * @throws ApiException if fails to make API call
   */
  public List<LiquidationAddressResponseDto> liquidationAddressControllerGetLiquidationAddresses(@javax.annotation.Nonnull String customerId, Map<String, String> headers) throws ApiException {
    ApiResponse<List<LiquidationAddressResponseDto>> localVarResponse = liquidationAddressControllerGetLiquidationAddressesWithHttpInfo(customerId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get all liquidation addresses for a customer
   * Retrieve all liquidation addresses associated with a specific customer.
   * @param customerId Unique identifier for the customer (required)
   * @return ApiResponse&lt;List&lt;LiquidationAddressResponseDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<LiquidationAddressResponseDto>> liquidationAddressControllerGetLiquidationAddressesWithHttpInfo(@javax.annotation.Nonnull String customerId) throws ApiException {
    return liquidationAddressControllerGetLiquidationAddressesWithHttpInfo(customerId, null);
  }

  /**
   * Get all liquidation addresses for a customer
   * Retrieve all liquidation addresses associated with a specific customer.
   * @param customerId Unique identifier for the customer (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;LiquidationAddressResponseDto&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<LiquidationAddressResponseDto>> liquidationAddressControllerGetLiquidationAddressesWithHttpInfo(@javax.annotation.Nonnull String customerId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = liquidationAddressControllerGetLiquidationAddressesRequestBuilder(customerId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("liquidationAddressControllerGetLiquidationAddresses", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<List<LiquidationAddressResponseDto>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        List<LiquidationAddressResponseDto> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<LiquidationAddressResponseDto>>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<List<LiquidationAddressResponseDto>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder liquidationAddressControllerGetLiquidationAddressesRequestBuilder(@javax.annotation.Nonnull String customerId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'customerId' is set
    if (customerId == null) {
      throw new ApiException(400, "Missing the required parameter 'customerId' when calling liquidationAddressControllerGetLiquidationAddresses");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/customers/{customerId}/liquidation_addresses"
        .replace("{customerId}", ApiClient.urlEncode(customerId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
