/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import java.math.BigDecimal;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-19T14:30:15.336690+02:00[Africa/Lusaka]", comments = "Generator version: 7.17.0")
public class ProductsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public ProductsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public ProductsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a new product
   * Creates a new product with optional image uploads.      This endpoint allows you to create products with detailed information and multiple images.  ## Use Cases - Add new products to your catalog - Create products with multiple images - Set up product pricing and descriptions  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per product - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Premium Widget\&quot; description: \&quot;High-quality widget for all your needs\&quot; price: \&quot;99.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Required Fields - &#x60;name&#x60;: Product name - &#x60;price&#x60;: Product price (decimal number)  ## Optional Fields - &#x60;description&#x60;: Detailed product description - &#x60;images&#x60;: Product images (up to 10 files)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (required)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (required)
   * @param price Product price in the specified currency. Must be greater than 0. (required)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @throws ApiException if fails to make API call
   */
  public void productControllerCreate(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String description, @javax.annotation.Nonnull BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images) throws ApiException {
    productControllerCreate(name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, null);
  }

  /**
   * Create a new product
   * Creates a new product with optional image uploads.      This endpoint allows you to create products with detailed information and multiple images.  ## Use Cases - Add new products to your catalog - Create products with multiple images - Set up product pricing and descriptions  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per product - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Premium Widget\&quot; description: \&quot;High-quality widget for all your needs\&quot; price: \&quot;99.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Required Fields - &#x60;name&#x60;: Product name - &#x60;price&#x60;: Product price (decimal number)  ## Optional Fields - &#x60;description&#x60;: Detailed product description - &#x60;images&#x60;: Product images (up to 10 files)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (required)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (required)
   * @param price Product price in the specified currency. Must be greater than 0. (required)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerCreate(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String description, @javax.annotation.Nonnull BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    productControllerCreateWithHttpInfo(name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, headers);
  }

  /**
   * Create a new product
   * Creates a new product with optional image uploads.      This endpoint allows you to create products with detailed information and multiple images.  ## Use Cases - Add new products to your catalog - Create products with multiple images - Set up product pricing and descriptions  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per product - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Premium Widget\&quot; description: \&quot;High-quality widget for all your needs\&quot; price: \&quot;99.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Required Fields - &#x60;name&#x60;: Product name - &#x60;price&#x60;: Product price (decimal number)  ## Optional Fields - &#x60;description&#x60;: Detailed product description - &#x60;images&#x60;: Product images (up to 10 files)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (required)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (required)
   * @param price Product price in the specified currency. Must be greater than 0. (required)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerCreateWithHttpInfo(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String description, @javax.annotation.Nonnull BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images) throws ApiException {
    return productControllerCreateWithHttpInfo(name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, null);
  }

  /**
   * Create a new product
   * Creates a new product with optional image uploads.      This endpoint allows you to create products with detailed information and multiple images.  ## Use Cases - Add new products to your catalog - Create products with multiple images - Set up product pricing and descriptions  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per product - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Premium Widget\&quot; description: \&quot;High-quality widget for all your needs\&quot; price: \&quot;99.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Required Fields - &#x60;name&#x60;: Product name - &#x60;price&#x60;: Product price (decimal number)  ## Optional Fields - &#x60;description&#x60;: Detailed product description - &#x60;images&#x60;: Product images (up to 10 files)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (required)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (required)
   * @param price Product price in the specified currency. Must be greater than 0. (required)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerCreateWithHttpInfo(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String description, @javax.annotation.Nonnull BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerCreateRequestBuilder(name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerCreate", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerCreateRequestBuilder(@javax.annotation.Nonnull String name, @javax.annotation.Nonnull String description, @javax.annotation.Nonnull BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'name' is set
    if (name == null) {
      throw new ApiException(400, "Missing the required parameter 'name' when calling productControllerCreate");
    }
    // verify the required parameter 'description' is set
    if (description == null) {
      throw new ApiException(400, "Missing the required parameter 'description' when calling productControllerCreate");
    }
    // verify the required parameter 'price' is set
    if (price == null) {
      throw new ApiException(400, "Missing the required parameter 'price' when calling productControllerCreate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    if (name != null) {
        multiPartBuilder.addTextBody("name", name.toString());
    }
    if (description != null) {
        multiPartBuilder.addTextBody("description", description.toString());
    }
    if (price != null) {
        multiPartBuilder.addTextBody("price", price.toString());
    }
    if (currency != null) {
        multiPartBuilder.addTextBody("currency", currency.toString());
    }
    if (type != null) {
        multiPartBuilder.addTextBody("type", type.toString());
    }
    if (weight != null) {
        multiPartBuilder.addTextBody("weight", weight.toString());
    }
    if (unit != null) {
        multiPartBuilder.addTextBody("unit", unit.toString());
    }
    if (quantity != null) {
        multiPartBuilder.addTextBody("quantity", quantity.toString());
    }
    if (stockCount != null) {
        multiPartBuilder.addTextBody("stockCount", stockCount.toString());
    }
    if (status != null) {
        multiPartBuilder.addTextBody("status", status.toString());
    }
    if (productType != null) {
        multiPartBuilder.addTextBody("productType", productType.toString());
    }
    for (int i=0; i < images.size(); i++) {
        if (images.get(i) != null) {
            multiPartBuilder.addTextBody("images", images.get(i).toString());
        }
    }
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formOutputStream.toByteArray()));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all products
   * Retrieves a list of products with pagination.      This endpoint allows you to fetch products with optional pagination.  ## Use Cases - List all products - Browse product catalog - Implement product search  ## Query Parameters - &#x60;skip&#x60;: Number of records to skip (default: 0) - &#x60;take&#x60;: Number of records to take (default: 10)  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;data\&quot;: [     {       \&quot;id\&quot;: \&quot;prod_123456\&quot;,       \&quot;name\&quot;: \&quot;Premium Widget\&quot;,       \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,       \&quot;price\&quot;: \&quot;99.99\&quot;,       \&quot;images\&quot;: [         \&quot;https://storage.example.com/images/file1.jpg\&quot;,         \&quot;https://storage.example.com/images/file2.jpg\&quot;       ],       \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;     }   ],   \&quot;total\&quot;: 100,   \&quot;skip\&quot;: 0,   \&quot;take\&quot;: 10 } &#x60;&#x60;&#x60;
   * @param skip Number of records to skip (optional)
   * @param take Number of records to take (optional)
   * @throws ApiException if fails to make API call
   */
  public void productControllerFindAll(@javax.annotation.Nullable BigDecimal skip, @javax.annotation.Nullable BigDecimal take) throws ApiException {
    productControllerFindAll(skip, take, null);
  }

  /**
   * Get all products
   * Retrieves a list of products with pagination.      This endpoint allows you to fetch products with optional pagination.  ## Use Cases - List all products - Browse product catalog - Implement product search  ## Query Parameters - &#x60;skip&#x60;: Number of records to skip (default: 0) - &#x60;take&#x60;: Number of records to take (default: 10)  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;data\&quot;: [     {       \&quot;id\&quot;: \&quot;prod_123456\&quot;,       \&quot;name\&quot;: \&quot;Premium Widget\&quot;,       \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,       \&quot;price\&quot;: \&quot;99.99\&quot;,       \&quot;images\&quot;: [         \&quot;https://storage.example.com/images/file1.jpg\&quot;,         \&quot;https://storage.example.com/images/file2.jpg\&quot;       ],       \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;     }   ],   \&quot;total\&quot;: 100,   \&quot;skip\&quot;: 0,   \&quot;take\&quot;: 10 } &#x60;&#x60;&#x60;
   * @param skip Number of records to skip (optional)
   * @param take Number of records to take (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerFindAll(@javax.annotation.Nullable BigDecimal skip, @javax.annotation.Nullable BigDecimal take, Map<String, String> headers) throws ApiException {
    productControllerFindAllWithHttpInfo(skip, take, headers);
  }

  /**
   * Get all products
   * Retrieves a list of products with pagination.      This endpoint allows you to fetch products with optional pagination.  ## Use Cases - List all products - Browse product catalog - Implement product search  ## Query Parameters - &#x60;skip&#x60;: Number of records to skip (default: 0) - &#x60;take&#x60;: Number of records to take (default: 10)  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;data\&quot;: [     {       \&quot;id\&quot;: \&quot;prod_123456\&quot;,       \&quot;name\&quot;: \&quot;Premium Widget\&quot;,       \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,       \&quot;price\&quot;: \&quot;99.99\&quot;,       \&quot;images\&quot;: [         \&quot;https://storage.example.com/images/file1.jpg\&quot;,         \&quot;https://storage.example.com/images/file2.jpg\&quot;       ],       \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;     }   ],   \&quot;total\&quot;: 100,   \&quot;skip\&quot;: 0,   \&quot;take\&quot;: 10 } &#x60;&#x60;&#x60;
   * @param skip Number of records to skip (optional)
   * @param take Number of records to take (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerFindAllWithHttpInfo(@javax.annotation.Nullable BigDecimal skip, @javax.annotation.Nullable BigDecimal take) throws ApiException {
    return productControllerFindAllWithHttpInfo(skip, take, null);
  }

  /**
   * Get all products
   * Retrieves a list of products with pagination.      This endpoint allows you to fetch products with optional pagination.  ## Use Cases - List all products - Browse product catalog - Implement product search  ## Query Parameters - &#x60;skip&#x60;: Number of records to skip (default: 0) - &#x60;take&#x60;: Number of records to take (default: 10)  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;data\&quot;: [     {       \&quot;id\&quot;: \&quot;prod_123456\&quot;,       \&quot;name\&quot;: \&quot;Premium Widget\&quot;,       \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,       \&quot;price\&quot;: \&quot;99.99\&quot;,       \&quot;images\&quot;: [         \&quot;https://storage.example.com/images/file1.jpg\&quot;,         \&quot;https://storage.example.com/images/file2.jpg\&quot;       ],       \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;     }   ],   \&quot;total\&quot;: 100,   \&quot;skip\&quot;: 0,   \&quot;take\&quot;: 10 } &#x60;&#x60;&#x60;
   * @param skip Number of records to skip (optional)
   * @param take Number of records to take (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerFindAllWithHttpInfo(@javax.annotation.Nullable BigDecimal skip, @javax.annotation.Nullable BigDecimal take, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerFindAllRequestBuilder(skip, take, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerFindAll", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerFindAllRequestBuilder(@javax.annotation.Nullable BigDecimal skip, @javax.annotation.Nullable BigDecimal take, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "skip";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("skip", skip));
    localVarQueryParameterBaseName = "take";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("take", take));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a product by ID
   * Retrieves detailed information about a specific product.      This endpoint allows you to fetch complete product details including all images.  ## Use Cases - View product details - Display product information - Check product availability  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;id\&quot;: \&quot;prod_123456\&quot;,   \&quot;name\&quot;: \&quot;Premium Widget\&quot;,   \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,   \&quot;price\&quot;: \&quot;99.99\&quot;,   \&quot;images\&quot;: [     \&quot;https://storage.example.com/images/file1.jpg\&quot;,     \&quot;https://storage.example.com/images/file2.jpg\&quot;   ],   \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,   \&quot;updatedAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot; } &#x60;&#x60;&#x60;
   * @param id Product ID (required)
   * @throws ApiException if fails to make API call
   */
  public void productControllerFindOne(@javax.annotation.Nonnull String id) throws ApiException {
    productControllerFindOne(id, null);
  }

  /**
   * Get a product by ID
   * Retrieves detailed information about a specific product.      This endpoint allows you to fetch complete product details including all images.  ## Use Cases - View product details - Display product information - Check product availability  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;id\&quot;: \&quot;prod_123456\&quot;,   \&quot;name\&quot;: \&quot;Premium Widget\&quot;,   \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,   \&quot;price\&quot;: \&quot;99.99\&quot;,   \&quot;images\&quot;: [     \&quot;https://storage.example.com/images/file1.jpg\&quot;,     \&quot;https://storage.example.com/images/file2.jpg\&quot;   ],   \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,   \&quot;updatedAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot; } &#x60;&#x60;&#x60;
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerFindOne(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    productControllerFindOneWithHttpInfo(id, headers);
  }

  /**
   * Get a product by ID
   * Retrieves detailed information about a specific product.      This endpoint allows you to fetch complete product details including all images.  ## Use Cases - View product details - Display product information - Check product availability  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;id\&quot;: \&quot;prod_123456\&quot;,   \&quot;name\&quot;: \&quot;Premium Widget\&quot;,   \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,   \&quot;price\&quot;: \&quot;99.99\&quot;,   \&quot;images\&quot;: [     \&quot;https://storage.example.com/images/file1.jpg\&quot;,     \&quot;https://storage.example.com/images/file2.jpg\&quot;   ],   \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,   \&quot;updatedAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot; } &#x60;&#x60;&#x60;
   * @param id Product ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerFindOneWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return productControllerFindOneWithHttpInfo(id, null);
  }

  /**
   * Get a product by ID
   * Retrieves detailed information about a specific product.      This endpoint allows you to fetch complete product details including all images.  ## Use Cases - View product details - Display product information - Check product availability  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;id\&quot;: \&quot;prod_123456\&quot;,   \&quot;name\&quot;: \&quot;Premium Widget\&quot;,   \&quot;description\&quot;: \&quot;High-quality widget for all your needs\&quot;,   \&quot;price\&quot;: \&quot;99.99\&quot;,   \&quot;images\&quot;: [     \&quot;https://storage.example.com/images/file1.jpg\&quot;,     \&quot;https://storage.example.com/images/file2.jpg\&quot;   ],   \&quot;createdAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,   \&quot;updatedAt\&quot;: \&quot;2024-03-20T10:00:00Z\&quot; } &#x60;&#x60;&#x60;
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerFindOneWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerFindOneRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerFindOne", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerFindOneRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling productControllerFindOne");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a product
   * Deletes a product and its associated images.      This endpoint allows you to remove a product and all its associated data.  ## Use Cases - Remove discontinued products - Clean up product catalog - Delete test products  ## Notes - This action cannot be undone - All product images will be deleted - Associated data will be removed
   * @param id Product ID (required)
   * @throws ApiException if fails to make API call
   */
  public void productControllerRemove(@javax.annotation.Nonnull String id) throws ApiException {
    productControllerRemove(id, null);
  }

  /**
   * Delete a product
   * Deletes a product and its associated images.      This endpoint allows you to remove a product and all its associated data.  ## Use Cases - Remove discontinued products - Clean up product catalog - Delete test products  ## Notes - This action cannot be undone - All product images will be deleted - Associated data will be removed
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerRemove(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    productControllerRemoveWithHttpInfo(id, headers);
  }

  /**
   * Delete a product
   * Deletes a product and its associated images.      This endpoint allows you to remove a product and all its associated data.  ## Use Cases - Remove discontinued products - Clean up product catalog - Delete test products  ## Notes - This action cannot be undone - All product images will be deleted - Associated data will be removed
   * @param id Product ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerRemoveWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return productControllerRemoveWithHttpInfo(id, null);
  }

  /**
   * Delete a product
   * Deletes a product and its associated images.      This endpoint allows you to remove a product and all its associated data.  ## Use Cases - Remove discontinued products - Clean up product catalog - Delete test products  ## Notes - This action cannot be undone - All product images will be deleted - Associated data will be removed
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerRemoveWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerRemoveRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerRemove", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerRemoveRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling productControllerRemove");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a product
   * Updates an existing product&#39;s information and optionally adds new images.      This endpoint allows you to modify product details and manage product images.  ## Use Cases - Update product information - Change product pricing - Modify product images - Update product description  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Updated Premium Widget\&quot; description: \&quot;Updated description\&quot; price: \&quot;129.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Notes - Only include fields that need to be updated - New images will replace existing images - Maximum 10 images per product - Images are automatically optimized
   * @param id Product ID (required)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (optional)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (optional)
   * @param price Product price in the specified currency. Must be greater than 0. (optional)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @throws ApiException if fails to make API call
   */
  public void productControllerUpdate(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images) throws ApiException {
    productControllerUpdate(id, name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, null);
  }

  /**
   * Update a product
   * Updates an existing product&#39;s information and optionally adds new images.      This endpoint allows you to modify product details and manage product images.  ## Use Cases - Update product information - Change product pricing - Modify product images - Update product description  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Updated Premium Widget\&quot; description: \&quot;Updated description\&quot; price: \&quot;129.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Notes - Only include fields that need to be updated - New images will replace existing images - Maximum 10 images per product - Images are automatically optimized
   * @param id Product ID (required)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (optional)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (optional)
   * @param price Product price in the specified currency. Must be greater than 0. (optional)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerUpdate(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    productControllerUpdateWithHttpInfo(id, name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, headers);
  }

  /**
   * Update a product
   * Updates an existing product&#39;s information and optionally adds new images.      This endpoint allows you to modify product details and manage product images.  ## Use Cases - Update product information - Change product pricing - Modify product images - Update product description  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Updated Premium Widget\&quot; description: \&quot;Updated description\&quot; price: \&quot;129.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Notes - Only include fields that need to be updated - New images will replace existing images - Maximum 10 images per product - Images are automatically optimized
   * @param id Product ID (required)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (optional)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (optional)
   * @param price Product price in the specified currency. Must be greater than 0. (optional)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerUpdateWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images) throws ApiException {
    return productControllerUpdateWithHttpInfo(id, name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, null);
  }

  /**
   * Update a product
   * Updates an existing product&#39;s information and optionally adds new images.      This endpoint allows you to modify product details and manage product images.  ## Use Cases - Update product information - Change product pricing - Modify product images - Update product description  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; name: \&quot;Updated Premium Widget\&quot; description: \&quot;Updated description\&quot; price: \&quot;129.99\&quot; images: [file1.jpg, file2.jpg]  // Optional, up to 10 images &#x60;&#x60;&#x60;  ## Notes - Only include fields that need to be updated - New images will replace existing images - Maximum 10 images per product - Images are automatically optimized
   * @param id Product ID (required)
   * @param name Product name as it will appear to customers. Should be clear and descriptive. (optional)
   * @param description Detailed description of the product. Supports markdown formatting for rich text display. (optional)
   * @param price Product price in the specified currency. Must be greater than 0. (optional)
   * @param currency Currency code for the price. Defaults to USD if not specified. (optional, default to USD)
   * @param type Product type (optional)
   * @param weight Weight of the product (optional)
   * @param unit Unit of measurement (optional)
   * @param quantity Quantity available (optional)
   * @param stockCount Stock count (optional)
   * @param status Product status (optional)
   * @param productType Product type (optional)
   * @param images Array of image URLs (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerUpdateWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerUpdateRequestBuilder(id, name, description, price, currency, type, weight, unit, quantity, stockCount, status, productType, images, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerUpdate", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerUpdateRequestBuilder(@javax.annotation.Nonnull String id, @javax.annotation.Nullable String name, @javax.annotation.Nullable String description, @javax.annotation.Nullable BigDecimal price, @javax.annotation.Nullable String currency, @javax.annotation.Nullable String type, @javax.annotation.Nullable BigDecimal weight, @javax.annotation.Nullable String unit, @javax.annotation.Nullable BigDecimal quantity, @javax.annotation.Nullable BigDecimal stockCount, @javax.annotation.Nullable String status, @javax.annotation.Nullable String productType, @javax.annotation.Nullable List<String> images, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling productControllerUpdate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    if (name != null) {
        multiPartBuilder.addTextBody("name", name.toString());
    }
    if (description != null) {
        multiPartBuilder.addTextBody("description", description.toString());
    }
    if (price != null) {
        multiPartBuilder.addTextBody("price", price.toString());
    }
    if (currency != null) {
        multiPartBuilder.addTextBody("currency", currency.toString());
    }
    if (type != null) {
        multiPartBuilder.addTextBody("type", type.toString());
    }
    if (weight != null) {
        multiPartBuilder.addTextBody("weight", weight.toString());
    }
    if (unit != null) {
        multiPartBuilder.addTextBody("unit", unit.toString());
    }
    if (quantity != null) {
        multiPartBuilder.addTextBody("quantity", quantity.toString());
    }
    if (stockCount != null) {
        multiPartBuilder.addTextBody("stockCount", stockCount.toString());
    }
    if (status != null) {
        multiPartBuilder.addTextBody("status", status.toString());
    }
    if (productType != null) {
        multiPartBuilder.addTextBody("productType", productType.toString());
    }
    for (int i=0; i < images.size(); i++) {
        if (images.get(i) != null) {
            multiPartBuilder.addTextBody("images", images.get(i).toString());
        }
    }
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formOutputStream.toByteArray()));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("PUT", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Upload images for a product
   * Adds new images to an existing product.      This endpoint allows you to upload additional images for a product that already exists.  ## Use Cases - Add more product images - Update product gallery - Enhance product presentation  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per upload - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; images: [file1.jpg, file2.jpg]  // Up to 10 images &#x60;&#x60;&#x60;  ## Notes - Images are appended to existing product images - Total images per product cannot exceed 10 - Images are automatically optimized and resized
   * @param id Product ID (required)
   * @throws ApiException if fails to make API call
   */
  public void productControllerUploadImage(@javax.annotation.Nonnull String id) throws ApiException {
    productControllerUploadImage(id, null);
  }

  /**
   * Upload images for a product
   * Adds new images to an existing product.      This endpoint allows you to upload additional images for a product that already exists.  ## Use Cases - Add more product images - Update product gallery - Enhance product presentation  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per upload - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; images: [file1.jpg, file2.jpg]  // Up to 10 images &#x60;&#x60;&#x60;  ## Notes - Images are appended to existing product images - Total images per product cannot exceed 10 - Images are automatically optimized and resized
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void productControllerUploadImage(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    productControllerUploadImageWithHttpInfo(id, headers);
  }

  /**
   * Upload images for a product
   * Adds new images to an existing product.      This endpoint allows you to upload additional images for a product that already exists.  ## Use Cases - Add more product images - Update product gallery - Enhance product presentation  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per upload - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; images: [file1.jpg, file2.jpg]  // Up to 10 images &#x60;&#x60;&#x60;  ## Notes - Images are appended to existing product images - Total images per product cannot exceed 10 - Images are automatically optimized and resized
   * @param id Product ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerUploadImageWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
    return productControllerUploadImageWithHttpInfo(id, null);
  }

  /**
   * Upload images for a product
   * Adds new images to an existing product.      This endpoint allows you to upload additional images for a product that already exists.  ## Use Cases - Add more product images - Update product gallery - Enhance product presentation  ## Supported Image Formats - JPEG/JPG - PNG - WebP - Maximum 10 images per upload - Maximum file size: 5MB per image  ## Example Request (multipart/form-data) &#x60;&#x60;&#x60; images: [file1.jpg, file2.jpg]  // Up to 10 images &#x60;&#x60;&#x60;  ## Notes - Images are appended to existing product images - Total images per product cannot exceed 10 - Images are automatically optimized and resized
   * @param id Product ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> productControllerUploadImageWithHttpInfo(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = productControllerUploadImageRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("productControllerUploadImage", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder productControllerUploadImageRequestBuilder(@javax.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling productControllerUploadImage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v0/products/{id}/images"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
