/*
 * Devdraft AI Payment & Business Management API
 *  A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.     
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import java.math.BigDecimal;
import org.openapitools.client.model.CreateCustomerDto;
import org.openapitools.client.model.CustomerStatus;
import java.util.UUID;
import org.openapitools.client.model.UpdateCustomerDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for CustomersApi
 */
@Disabled
public class CustomersApiTest {

    private final CustomersApi api = new CustomersApi();

    
    /**
     * Create a new customer
     *
     * Creates a new customer in the system with their personal and contact information.      This endpoint allows you to register new customers and store their details for future transactions.  ## Use Cases - Register new customers for payment processing - Store customer information for recurring payments - Maintain customer profiles for transaction history  ## Example: Create New Customer &#x60;&#x60;&#x60;json {   \&quot;first_name\&quot;: \&quot;John\&quot;,   \&quot;last_name\&quot;: \&quot;Doe\&quot;,   \&quot;email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;phone_number\&quot;: \&quot;+1-555-123-4567\&quot;,   \&quot;customer_type\&quot;: \&quot;Startup\&quot;,   \&quot;status\&quot;: \&quot;ACTIVE\&quot; } &#x60;&#x60;&#x60;  ## Required Fields - &#x60;first_name&#x60;: Customer&#39;s first name (1-100 characters) - &#x60;last_name&#x60;: Customer&#39;s last name (1-100 characters) - &#x60;phone_number&#x60;: Customer&#39;s phone number (max 20 characters)  ## Optional Fields - &#x60;email&#x60;: Valid email address (max 255 characters) - &#x60;customer_type&#x60;: Type of customer account (Individual, Startup, Small Business, Medium Business, Enterprise, Non-Profit, Government) - &#x60;status&#x60;: Customer status (ACTIVE, BLACKLISTED, DEACTIVATED)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerControllerCreateTest() throws ApiException {
        CreateCustomerDto createCustomerDto = null;
        
        api.customerControllerCreate(createCustomerDto);
        
        // TODO: test validations
    }
    
    /**
     * Get all customers with filters
     *
     * Retrieves a list of customers with optional filtering and pagination.      This endpoint allows you to search and filter customers based on various criteria.  ## Use Cases - List all customers with pagination - Search customers by name or email - Filter customers by status - Export customer data  ## Query Parameters - &#x60;skip&#x60;: Number of records to skip (default: 0, min: 0) - &#x60;take&#x60;: Number of records to take (default: 10, min: 1, max: 100) - &#x60;status&#x60;: Filter by customer status (ACTIVE, BLACKLISTED, DEACTIVATED) - &#x60;name&#x60;: Filter by customer name (partial match, case-insensitive) - &#x60;email&#x60;: Filter by customer email (exact match, case-insensitive)  ## Example Request &#x60;GET /api/v0/customers?skip&#x3D;0&amp;take&#x3D;20&amp;status&#x3D;ACTIVE&amp;name&#x3D;John&#x60;  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;data\&quot;: [     {       \&quot;id\&quot;: \&quot;cust_123456\&quot;,       \&quot;first_name\&quot;: \&quot;John\&quot;,       \&quot;last_name\&quot;: \&quot;Doe\&quot;,       \&quot;email\&quot;: \&quot;john.doe@example.com\&quot;,       \&quot;phone_number\&quot;: \&quot;+1-555-123-4567\&quot;,       \&quot;customer_type\&quot;: \&quot;Startup\&quot;,       \&quot;status\&quot;: \&quot;ACTIVE\&quot;,       \&quot;created_at\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,       \&quot;updated_at\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;     }   ],   \&quot;total\&quot;: 100,   \&quot;skip\&quot;: 0,   \&quot;take\&quot;: 10 } &#x60;&#x60;&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerControllerFindAllTest() throws ApiException {
        BigDecimal skip = null;
        BigDecimal take = null;
        CustomerStatus status = null;
        String name = null;
        String email = null;
        
        api.customerControllerFindAll(skip, take, status, name, email);
        
        // TODO: test validations
    }
    
    /**
     * Get a customer by ID
     *
     * Retrieves detailed information about a specific customer.      This endpoint allows you to fetch complete customer details including their contact information and status.  ## Use Cases - View customer details - Verify customer information - Check customer status before processing payments  ## Path Parameters - &#x60;id&#x60;: Customer UUID (required) - Must be a valid UUID format  ## Example Request &#x60;GET /api/v0/customers/123e4567-e89b-12d3-a456-426614174000&#x60;  ## Example Response &#x60;&#x60;&#x60;json {   \&quot;id\&quot;: \&quot;cust_123456\&quot;,   \&quot;first_name\&quot;: \&quot;John\&quot;,   \&quot;last_name\&quot;: \&quot;Doe\&quot;,   \&quot;email\&quot;: \&quot;john.doe@example.com\&quot;,   \&quot;phone_number\&quot;: \&quot;+1-555-123-4567\&quot;,   \&quot;customer_type\&quot;: \&quot;Enterprise\&quot;,   \&quot;status\&quot;: \&quot;ACTIVE\&quot;,   \&quot;last_spent\&quot;: 1250.50,   \&quot;last_purchase_date\&quot;: \&quot;2024-03-15T14:30:00Z\&quot;,   \&quot;created_at\&quot;: \&quot;2024-03-20T10:00:00Z\&quot;,   \&quot;updated_at\&quot;: \&quot;2024-03-20T10:00:00Z\&quot; } &#x60;&#x60;&#x60;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerControllerFindOneTest() throws ApiException {
        UUID id = null;
        
        api.customerControllerFindOne(id);
        
        // TODO: test validations
    }
    
    /**
     * Update a customer
     *
     * Updates an existing customer&#39;s information.      This endpoint allows you to modify customer details while preserving their core information.  ## Use Cases - Update customer contact information - Change customer type - Modify customer status  ## Path Parameters - &#x60;id&#x60;: Customer UUID (required) - Must be a valid UUID format  ## Example Request &#x60;PATCH /api/v0/customers/123e4567-e89b-12d3-a456-426614174000&#x60;  ## Example Request Body &#x60;&#x60;&#x60;json {   \&quot;first_name\&quot;: \&quot;John\&quot;,   \&quot;last_name\&quot;: \&quot;Smith\&quot;,   \&quot;phone_number\&quot;: \&quot;+1-987-654-3210\&quot;,   \&quot;customer_type\&quot;: \&quot;Small Business\&quot; } &#x60;&#x60;&#x60;  ## Notes - Only include fields that need to be updated - All fields are optional in updates - Status changes may require additional verification
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void customerControllerUpdateTest() throws ApiException {
        UUID id = null;
        UpdateCustomerDto updateCustomerDto = null;
        
        api.customerControllerUpdate(id, updateCustomerDto);
        
        // TODO: test validations
    }
    
}
